### ISSUE TITLE
Segmentation fault after update to 4.11.1

### ISSUE THREAD

**Issue by concept47** [appoptics/appoptics-apm-ruby#111]
After we updated to Gem version to 4.11.1 to work with Ruby 2.7.1 we started seeing sporadic segfaults, usually on shut downs of old workers while we spin up new ones in the deploy process. Seeing this in both when we run in heroku or docker on AWS, mostly around sidekiq swarm. 

Upgrading to 4.12.1 makes the problem much worse, with the segfaults happening once every few seconds after the upgrade vs at the end of deploys (couple of times a day). The stack trace for the 4.12.1 are much more exotic, longer and difficult to understand. 

OS: Heroku or Debian GNU/Linux 10 in Docker container on AWS
Ruby: ruby 2.7.1p83 + Rails 6.0.3.4 (with bootsnap 1.4.5)
Log

```
TID-1bno INFO: Booting Sidekiq 5.2.7 with redis options {:id=>"Sidekiq-server-PID-4", :url=>"redis://h:REDACTED@ec2-xxx.compute-1.amazonaws.com:xxx"}
Oct 28 23:58:06 app[worker] info /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-ent-1.8.1/lib/sidekiq-ent/swarm.rb:191: [BUG] Segmentation fault at 0x0000000000000480
Oct 28 23:58:06 app[worker] info ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
Oct 28 23:58:06 app[worker] info
Oct 28 23:58:06 app[worker] info -- Machine register context ------------------------------------------------
Oct 28 23:58:06 app[worker] info  RIP: 0x00007f7d8d83ff76 RBP: 0x0000000000000000 RSP: 0x00007f7d5abfa650
Oct 28 23:58:06 app[worker] info  RAX: 0x0000000000000000 RBX: 0x00007f7d51386bb8 RCX: 0x00007f7d5abfaeb8
Oct 28 23:58:06 app[worker] info  RDX: 0x00007f7d7b7eeb90 RDI: 0x00007f7d51386bb8 RSI: 0x0000000000000013
Oct 28 23:58:06 app[worker] info   R8: 0x0000000000000000  R9: 0x00007f7d57407c60 R10: 0x000000000801ce00
Oct 28 23:58:06 app[worker] info  R11: 0x0000000000000000 R12: 0x0000000000000020 R13: 0x00007f7d8cbb5320
Oct 28 23:58:06 app[worker] info  R14: 0x00007f7d8cbb5520 R15: 0x00007f7d8cbb53a0 EFL: 0x0000000000010206
Oct 28 23:58:06 app[worker] info
Oct 28 23:58:06 app[worker] info -- C level backtrace information -------------------------------------------
Oct 28 23:58:06 app[worker] info /app/vendor/ruby-2.7.1/bin/../lib/libruby.so.2.7(rb_vm_bugreport+0x7ce) [0x7f7d8d9fc02e] vm_dump.c:755
Oct 28 23:58:06 app[worker] info /app/vendor/ruby-2.7.1/bin/../lib/libruby.so.2.7(rb_bug_for_fatal_signal+0xe7) [0x7f7d8d81b207] error.c:658
Oct 28 23:58:06 app[worker] info /app/vendor/ruby-2.7.1/bin/../lib/libruby.so.2.7(sigsegv+0x4b) [0x7f7d8d96007b] signal.c:946
Oct 28 23:58:06 app[worker] info /lib/x86_64-linux-gnu/libc.so.6(0x7f7d8d39dfd0) [0x7f7d8d39dfd0]
Oct 28 23:58:06 app[worker] info /app/vendor/ruby-2.7.1/bin/../lib/libruby.so.2.7(ruby_sized_xfree+0x3) [0x7f7d8d83ff76] gc.c:10164
Oct 28 23:58:06 app[worker] info /app/vendor/ruby-2.7.1/bin/../lib/libruby.so.2.7(ruby_xfree) gc.c:10171
Oct 28 23:58:06 app[worker] info /lib/x86_64-linux-gnu/libpthread.so.0(__nptl_deallocate_tsd.part.5+0x98) [0x7f7d8c9a1408]
Oct 28 23:58:06 app[worker] info /lib/x86_64-linux-gnu/libpthread.so.0(0x781b) [0x7f7d8c9a281b]
Oct 28 23:58:06 app[worker] info /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f7d8d480a3f]
Oct 28 23:58:06 app[worker] info
Oct 28 23:58:06 app[worker] info -- Other runtime information -----------------------------------------------
```

**Comment by prettycoder** [comment]
sorry to hear
Is it only the sidekiq workers that segfault or the whole app?
Only on shutdown?
Would you mind sending me more info so that I can try to reproduce and fix?
- Full stack traces for both cases 4.11.1 and 4.12.1
- Gemfile and Gemfile.lock
Probably best by email: maia.engeli@solarwinds.com

**Comment by prettycoder** [comment]
I'm tempted to close this, because I'm not able to reproduce
Are you using grpc? The use of grpc is the main difference in the c-library

**Comment by concept47** [comment]
No we’re not. I’ll have to make time to sit down and mail you the stack trace. Just got busy and it’s pretty long and pretty hard to figure out where to start and end

________________________________

**Comment by prettycoder** [comment]
ok, no worries, I'll wait ...

**Comment by concept47** [comment]
I'm going to go ahead and close this. getting the entire stack trace is just a massive pain with our logging system, (hard to know where the stack starts and ends) and we're going to be moving off appoptics in a few days. 

thanks for the helping out!
