### ISSUE TITLE
RubyGems and Github naming mismatch

### ISSUE THREAD

**Issue by mensfeld** [appoptics/appoptics-apm-ruby#119]
Hey,

My name is Maciej Mensfeld and I run a research security project called https://diffend.io.

I've noticed, that you have a mismatch between the repo name on GitHub (https://github.com/appoptics/appoptics-apm-ruby) and the RubyGems one (https://rubygems.org/gems/appoptics_apm).

This mismatch has been recently used as a brandjacking base for popular libraries like yours (it happened for one of the DataDog gems) thus I took courtesy and "booked" it for you (if you want).

If not, I'll just keep it as it is, protecting the https://rubygems.org/gems/appoptics-apm-ruby :)

If you want to transfer the ownership just please reach out to me.

Have a great day and thank you

ref https://rubygems.org/gems/appoptics_apm
ref https://github.com/appoptics/appoptics-apm-ruby
ref https://rubygems.org/gems/appoptics-apm-ruby

**Comment by prettycoder** [comment]
thanks for noticing and reserving
Let me see what we want to do

**Comment by prettycoder** [comment]
hi @mensfeld 
we would like to take over ownership of [https://rubygems.org/gems/appoptics-apm-ruby ](https://rubygems.org/gems/appoptics-apm-ruby )
Would you mind transferring it to maia@solarwinds.cloud? 
Thanks

**Comment by mensfeld** [comment]
@prettycoder sure thing. Would you mind mailing me from this email? (maciej@mensfeld.pl)

**Comment by prettycoder** [comment]
closing - thanks for your help @mensfield
