### ISSUE TITLE
[Bug] CRC verification verifies based on non hardcoded checksum

### ISSUE THREAD

**Issue by mensfeld** [appoptics/appoptics-apm-ruby#120]
it's me again: https://github.com/appoptics/appoptics-apm-ruby/issues/119

Oboe metal https://github.com/appoptics/appoptics-apm-ruby/blob/master/ext/oboe_metal/extconf.rb#L79 verifies the checksum but it uses an external resource to do it. This means that theoretically there could be a case where both files would have been tampered (let's say an employer breach) and the installation would pass.

Wouldn't it be better to ship the map of checksums with the gem and verify against a constant (as present in gem) list that cannot be tampered (without tampering RG gem itself)?

Thanks!

**Comment by prettycoder** [comment]
definitely :) 
thanks

**Comment by prettycoder** [comment]
fixed with new github action to create the gem
