### ISSUE TITLE
[Feature request] Extend the SDK to allow custom exception logging

### ISSUE THREAD

**Issue by prettycoder** [appoptics/appoptics-apm-ruby#74]
# Description
from: https://github.com/appoptics/appoptics-apm-ruby/pull/73
Extend the SDK to allow custom exception logging

# How to reproduce or use case
Question on the PR:

"What is the preferred way to send a custom exception to AppOptics APM, if not via log_start/log_exception/log_end? We're happy to change our approach to use a higher-level API if there's a better way."

**Comment by prettycoder** [comment]
Good question!

I haven't been asked for that, but it is good to know that there may be a use case for this.

The start_trace and trace SDK calls do rescue exceptions, log them, and reraise them.
But if you rescue the exception yourself, I guess log_exception is your friend for now. It can be called within the start_trace or trace block.

**Comment by chaddressler** [comment]
The use case here is when we encounter an exceptional condition that we want to take note of - and potentially be alerted for - but, for whatever reason, we don't want to raise an exception.  New Relic APM implements this through NewRelic::Agent.notice_error: https://www.rubydoc.info/github/newrelic/rpm/NewRelic%2FAgent:notice_error

**Comment by prettycoder** [comment]
I'm adding this as a feature request for an SDK call.

Feel free to use the API calls. We don't promote them because they can lead to broken traces if log_end isn't called (for example in the case when an exception happens).

I'm going to release a fix so that log_exception works properly in noop mode.
Hope this helps for now.

**Comment by chaddressler** [comment]
Sounds great - thanks for your help.

**Comment by prettycoder** [comment]
@chaddressler FYI:
appoptics_apm-4.7.0.gem was released this week with 2 new SDK methods `log_info` and `log_exception` that allow adding events to the current span.
Documentation here: https://www.rubydoc.info/github/appoptics/appoptics-apm-ruby/master/AppOpticsAPM/SDK/Logging
