### ISSUE TITLE
Disable instrumenting command line invocations

### ISSUE THREAD

**Issue by cheempz** [appoptics/appoptics-apm-ruby#8]
Some way to disable instrumenting command line invocations like rails routes or rake -T. 

Otherwise the agent's attempt to establish connection to the collector can slow things down perceptibly and generate distracting diagnostic info if connection cannot be made.

**Comment by prettycoder** [comment]
turns out this is easy to do, just wondering if we may turn off too much.
in appoptics_apm.rb add 1st line
```
return if ['rake', 'rails'].include File.basename($0)
```
