### ISSUE TITLE
Segmentation fault after update to 4.8.0

### ISSUE THREAD

**Issue by Jesterovskiy** [appoptics/appoptics-apm-ruby#83]
After I updated and deployed docker image with new version of appoptics apm, I get segmentation fault
Docker container in AWS ElasticBeanstalk
OS: Alpine linux 3.8
Ruby: 2.6.1p33
Log:
/app/vendor/bundle/ruby/2.6.0/gems/appoptics_apm-4.8.0/lib/appoptics_apm/support/transaction_settings.rb:53: [BUG] Segmentation fault at 0x0000000000000040
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0011 p:---- s:0107 e:000106 CFUNC  :getDecisions
c:0010 p:0192 s:0101 e:000100 METHOD /app/vendor/bundle/ruby/2.6.0/gems/appoptics_apm-4.8.0/lib/appoptics_apm/support/transaction_settings.rb:53 [FINISH]
c:0009 p:---- s:0090 e:000089 CFUNC  :new
c:0008 p:0119 s:0084 e:000083 METHOD /app/vendor/bundle/ruby/2.6.0/gems/appoptics_apm-4.8.0/lib/appoptics_apm/inst/rack.rb:42
c:0007 p:0020 s:0074 e:000073 METHOD /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:524
c:0006 p:0026 s:0068 e:000067 METHOD /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227
c:0005 p:0259 s:0063 e:000062 METHOD /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660
c:0004 p:0026 s:0038 e:000037 METHOD /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474
c:0003 p:0065 s:0026 e:000025 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334
c:0002 p:0127 s:0016 e:000015 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

**Comment by prettycoder** [comment]
Hi Jester,
thanks for reporting this. 
We are in the process of debugging and hope to have a fix soon.

**Comment by prettycoder** [comment]
gem version 4.8.1 is available from rubygems
A fix was needed in the C library for apps that use multiple threads.
