### ISSUE TITLE
[Bug] Missing configuration for rails 6

### ISSUE THREAD

**Issue by jeffblake** [appoptics/appoptics-apm-ruby#87]
# Description

Fails to boot for Rails 6 due to missing file.

`LoadError: cannot load such file -- appoptics_apm/frameworks/rails/inst/action_controller6`

**Comment by prettycoder** [comment]
Oh, thanks for pointing this out. 
I'll prioritize this and see if this would work with the same implementation as Rails 5.
If that's the case I may be able to push a release tomorrow.

**Comment by prettycoder** [comment]
Sorry, this will be delayed. Need to fix the integration and acceptance tests, so that they run with rails 6.

**Comment by prettycoder** [comment]
Fix in appoptics_apm-4.8.3.gem
it will not raise an error anymore. 
Rails 6 is not instrumented yet: Rack will still create a trace, but there will not be any Rails or Actionview traces. 
Rails 6 instrumentation coming soon.

**Comment by prettycoder** [comment]
now we also generate traces from Rails 6
https://github.com/appoptics/appoptics-apm-ruby/releases/tag/4.8.4
